stages:
  preprocess:
    cmd: python3 src/preprocess.py
    deps:
      - src/preprocess.py
    params:
      - config/preprocess.yaml:
        - seed
        - data_version
        - data_path
        - data_columns
        - target_name
        - min_tag_cnt
        - account_ids
        - embedding_pooling_type
    outs:
      - data/selected_tags.pkl

  train:
    cmd: python3 src/train.py
    deps:
      - src/train.py
      - data/selected_tags.pkl
    params:
      - config/preprocess.yaml:
        - seed
        - account_ids
        - data_version
        - target_name
        - min_tag_cnt
        - embedding_pooling_type
      - config/train.yaml:
        - experiment_name
        - train_path
        - tags_path
        - pca_n_components
        - models
    outs:
      - data/model_pipelines.pkl

  evaluate:
    cmd: python3 src/evaluate.py
    deps:
      - src/evaluate.py
      - data/model_pipelines.pkl
    params:
      - config/preprocess.yaml:
        - seed
        - account_ids
      - config/train.yaml:
        - experiment_name
      - config/evaluate.yaml:
        - test_path
        - model_path
        - result_path
        - result_path_track
    outs:
      - data/model_pipeline_performance_results.csv