preprocess:
  - seed: 42 # random state for reproducing experiments
  - data_columns: ["account_id", "contact_reason", "email_sentence_embeddings"] # list of columns
  - target_label: "contact_reason"
  - account_ids: ['49143'] # list of account ids
  - embedding_pooling_type: 'mean' # mean | max pooling
  - preprocess_type: 'single' # single | batch
