seed: 42 # random state for reproducing experiments
data_path: 'data/classification_dataset'
data_version: "v1" # version of the 
data_columns: # list of columns
  - account_id 
  - contact_reason
  - email_sentence_embeddings 
target_name: "contact_reason"
min_tag_cnt: 10
account_ids: # list of account ids
  - '49143' 
  - '23777'
  - '4453'
  - '81813'
  - '89195'
  - '12167'
  - '23353'
  - '62537'
  - '47355'
  - '65210'
embedding_pooling_type: 'mean' # mean | max pooling
