# config.yaml
prod:
  train:
    data_path: data/classification_dataset
    params:
      data_path: 'data/classification_dataset'
      data_version: "v1" 
      data_columns:
        - account_id 
        - contact_reason
        - email_sentence_embeddings 
      embedding_pooling_type: 'mean'
    model_path: results/models/final_model_pipelines_v1.pkl
  inference:
    model_path: results/models/final_model_pipelines_v1.pkl
    predictions: results/predictions.csv
