# merchant_config.yaml
# merchant specific model deployment status: ONBOARD -> MONITORING -> RETIRED
# ONBOARD - the model for specific merchant is trained and onboarded into the system. The model is ready to run inference in a shadow mode.
# MONITORING - the model is ready to run inference in a production mode.
# RETIRED - the model stopped running inference in a production mode.
'49143': 'ONBOARD' 
'23777': 'ONBOARD'
'4453': 'ONBOARD'
'81813': 'ONBOARD'
'89195': 'ONBOARD'
'12167': 'ONBOARD'
'23353': 'ONBOARD'
'62537': 'ONBOARD'
'47355': 'ONBOARD'
'65210': 'ONBOARD'